site_name: cloudflight-libsonnet
extra:
  version:
    provider: mike
plugins:
  - git-revision-date
  - search
theme:
  name: material
  icon:
    logo: material/kubernetes
  features:
    - navigation.tabs
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_name: "cloudflight-libsonnet"
repo_url: https://github.com/cloudflightio/cloudflight-libsonnet
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
